#############################################################################
# Makefile for building: scheduler
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue May 9 22:02:50 2017
# Project:  scheduler.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile scheduler.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++14 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		group_profile.cpp \
		teacher_profile.cpp \
		group_dialog.cpp \
		database.cpp \
		teacher_dialog.cpp \
		kernel/tree_solver.cpp \
		index_table.cpp moc_mainwindow.cpp \
		moc_group_dialog.cpp \
		moc_teacher_dialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		group_profile.o \
		teacher_profile.o \
		group_dialog.o \
		database.o \
		teacher_dialog.o \
		tree_solver.o \
		index_table.o \
		moc_mainwindow.o \
		moc_group_dialog.o \
		moc_teacher_dialog.o
DIST          = right-arrow.png \
		left-arrow.png \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		scheduler.pro
QMAKE_TARGET  = scheduler
DESTDIR       = 
TARGET        = scheduler

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_group_dialog.h ui_teacher_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: scheduler.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile scheduler.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile scheduler.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/scheduler1.0.0 || $(MKDIR) .tmp/scheduler1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/scheduler1.0.0/ && $(COPY_FILE) --parents mainwindow.h group_profile.h teacher_profile.h group_dialog.h database.h teacher_dialog.h kernel/tree_solver.h kernel/common_defines.h kernel/common_defines.h index_table.h .tmp/scheduler1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp group_profile.cpp teacher_profile.cpp group_dialog.cpp database.cpp teacher_dialog.cpp kernel/tree_solver.cpp index_table.cpp .tmp/scheduler1.0.0/ && $(COPY_FILE) --parents mainwindow.ui group_dialog.ui teacher_dialog.ui .tmp/scheduler1.0.0/ && (cd `dirname .tmp/scheduler1.0.0` && $(TAR) scheduler1.0.0.tar scheduler1.0.0 && $(COMPRESS) scheduler1.0.0.tar) && $(MOVE) `dirname .tmp/scheduler1.0.0`/scheduler1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/scheduler1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_group_dialog.cpp moc_teacher_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_group_dialog.cpp moc_teacher_dialog.cpp
moc_mainwindow.cpp: database.h \
		group_profile.h \
		index_table.h \
		teacher_profile.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_group_dialog.cpp: database.h \
		group_profile.h \
		index_table.h \
		teacher_profile.h \
		group_dialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) group_dialog.h -o moc_group_dialog.cpp

moc_teacher_dialog.cpp: database.h \
		group_profile.h \
		index_table.h \
		teacher_profile.h \
		teacher_dialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) teacher_dialog.h -o moc_teacher_dialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_group_dialog.h ui_teacher_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_group_dialog.h ui_teacher_dialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_group_dialog.h: group_dialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic group_dialog.ui -o ui_group_dialog.h

ui_teacher_dialog.h: teacher_dialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic teacher_dialog.ui -o ui_teacher_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		database.h \
		group_profile.h \
		index_table.h \
		teacher_profile.h \
		kernel/tree_solver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp group_dialog.h \
		database.h \
		group_profile.h \
		index_table.h \
		teacher_profile.h \
		teacher_dialog.h \
		mainwindow.h \
		ui_mainwindow.h \
		kernel/tree_solver.h \
		kernel/common_defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

group_profile.o: group_profile.cpp group_profile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o group_profile.o group_profile.cpp

teacher_profile.o: teacher_profile.cpp teacher_profile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o teacher_profile.o teacher_profile.cpp

group_dialog.o: group_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o group_dialog.o group_dialog.cpp

database.o: database.cpp database.h \
		group_profile.h \
		index_table.h \
		teacher_profile.h \
		kernel/common_defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

teacher_dialog.o: teacher_dialog.cpp teacher_dialog.h \
		database.h \
		group_profile.h \
		index_table.h \
		teacher_profile.h \
		ui_teacher_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o teacher_dialog.o teacher_dialog.cpp

tree_solver.o: kernel/tree_solver.cpp kernel/tree_solver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tree_solver.o kernel/tree_solver.cpp

index_table.o: index_table.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o index_table.o index_table.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_group_dialog.o: moc_group_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_group_dialog.o moc_group_dialog.cpp

moc_teacher_dialog.o: moc_teacher_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_teacher_dialog.o moc_teacher_dialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

